name: pharmacophore-toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - datamol
  - cairo  # ensures Cairo installation
  - pip
  - pip:
      - pandas
      - numpy
      - CairoSVG
      - py3Dmol
      - ipywidgets
#      - pharmacophore-toolkit
