# Services for multipage Streamlit app
-
  name: 'Welcome'
  description: 'Home Page'
  url: 'Home.py'

-
  name: 'Molecule Sketcher'
  description: 'Draw Molecules'
  url: 'Molecule-Sketcher.py'

-
  name: 'Protein'
  description: 'Protein'
  url: 'Protein.py'

-
  name: 'Changelog'
  description: 'Changelog'
  url: 'Changelog.py'

